[project]
name = "convlstm-abnormal-human-activity-recognition"
version = "0.1.0"
description = "An implementation of an Abnormal Human Activity Recognition Model that is based on ConvLSTM"
authors = [
    {name = "Sanele Hlabisa <hlabisasanele730@gmail.com>"}
]
license = {text = "Apache 2.0"}
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "av==16.1.0",
    "kagglehub==1.0.2",
    "matplotlib==3.10.8",
    "numpy==2.4.3",
    "pandas==2.3.3",
    "scikit-learn==1.8.0",
    "torch==2.9.1",
    "torchmetrics==1.8.2",
    "torchvision==0.24.1",
    "tqdm==4.67.3"
]

[tool.poetry]
packages = [{include = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pylint (>=4.0.2,<5.0.0)",
    "black (>=25.9.0,<26.0.0)"
]
